# use Ctrl-Space for prefix, double for nested
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# use bash
set -g default-shell /bin/bash

# enable mouse features for terminals that support it
set -g mouse-resize-pane on
set -g mouse-select-pane on
set -g mouse-select-window on

# use nice colors
source ~/.tmux/tmuxcolors.conf

# load some plugins
source ~/.tmux/tpm.conf
