# use Ctrl-Space for prefix, double for nested
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# use bash
set -g default-shell /bin/bash

# disable mouse
setw -g mode-mouse off
set -g mouse-select-pane off
set -g mouse-resize-pane off
set -g mouse-select-window off

# load some plugins
source ~/.tmux/tpm.conf

# use nice colors
source ~/.tmux/tmuxcolors.conf



# shorten command delay
set -sg escape-time 1

# set window and pane index to 1 (0 by default)
set-option -g base-index 1
setw -g pane-base-index 1

set-option -g status on
set -g status-utf8 on
set -g status-justify left

# visual notification of activity in other windows
setw -g monitor-activity on
set -g visual-activity on
set -g visual-bell on

set -g status-right-length 40
set -g status-right "\"#T\" %e-%m-%y %R"

set -g status-left-length 40
set -g status-left "[#S] #h #I:#P "