# http://madebynathan.com/2011/10/04/a-nicer-way-to-use-xclip/

# A shortcut function that simplifies usage of xclip.
# - Accepts input from either stdin (pipe), or params.
# ------------------------------------------------
cb() {
  local xclip
  local xclipparam

  case "$platform" in
    "mac")
      xclip="pbcopy"
      xclipparam=""
      ;;
    *)
      xclip="xclip"
      xclipparam="-selection x"
      ;;
  esac

  if ! type "$xclip" > /dev/null 2>&1; then
    echo -e "$consoleWarn""You must have the '"$xclip"' program installed.""$consoleReset"

  elif [[ "$USER" == "root" ]]; then
    echo -e "$consoleWarn""Must be regular user (not root) to copy a file to the clipboard.""$consoleReset"

  else
    if ! [[ "$( tty )" == /dev/* ]]; then
      input="$(< /dev/stdin)"
    else
      input="$*"
    fi

    if [ -z "$input" ]; then
      echo "Copies a string to the clipboard."
      echo "Usage: cb <string>"
      echo "       echo <string> | cb"
    else
      echo -n "$input" | "$xclip" $xclipparam
      if [ ${#input} -gt 80 ]; then input="$(echo $input | cut -c1-80)..."; fi
      echo -e "Copied to clipboard: $input"
    fi
  fi

  unset xclip xclipparam
}

# Aliases / functions leveraging the cb() function
# ------------------------------------------------

# Copy contents of a file
function cbf() { cat "$1" | cb; }  

# Copy SSH public key
alias cbssh="cbf ~/.ssh/id_rsa.pub"  

# Copy current working directory
alias cbwd="pwd | cb"  

# Copy most recent command in bash history
alias cbhs="cat $HISTFILE | tail -n 1 | cb"  